MvcApp/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MvcApp.Models;
using Biblioteca.Modelos;

namespace MvcApp.Controllers
{

    [Authorize]
    public class ContaController : Controller
    {
        private ContextoDoTuiter contexto;

        public ContaController(){
            contexto = new ContextoDoTuiter();
        }

        //
        // GET: /Account/LogOn

        [AllowAnonymous]
        public ActionResult Entrar()
        {
            return ContextDependentView();
        }

        [AllowAnonymous]
        [HttpPost]
        public JsonResult JsonEntrar(LogOnModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (ValidarUsuario(model.Email, model.Senha))
                {
                    FormsAuthentication.SetAuthCookie(model.Email, model.Lembrar);
                    return Json(new { success = true, redirect = returnUrl });
                }
                else
                {
                    ModelState.AddModelError("", "O e-mail ou senha estão incorretos");
                }
            }

            // If we got this far, something failed
            return Json(new { errors = ModelState.ToArray() });
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Entrar(LogOnModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (ValidarUsuario(model.Email, model.Senha))
                {
                    FormsAuthentication.SetAuthCookie(model.Email, model.Lembrar);
                    if (Url.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "O e-mail ou senha estão incorretos");
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        public ActionResult Sair()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        public ActionResult Registrar()
        {
            return ContextDependentView();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult JsonRegistrar(Usuario model)
        {
            if (ModelState.IsValid)
            {
                try
                { 
                    CriarUsuario(model);
                    FormsAuthentication.SetAuthCookie(model.Email, createPersistentCookie: false);
                    return Json(new { success = true });
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            // If we got this far, something failed
            return Json(new { errors = ModelState.ToArray() });
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Registrar(Usuario model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    CriarUsuario(model);
                    FormsAuthentication.SetAuthCookie(model.Email, createPersistentCookie: false);
                    return RedirectToAction("Index", "Home");
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        private ActionResult ContextDependentView()
        {
            string actionName = ControllerContext.RouteData.GetRequiredString("action");
            if (Request.QueryString["content"] != null)
            {
                ViewBag.FormAction = "Json" + actionName;
                return PartialView();
            }
            else
            {
                ViewBag.FormAction = actionName;
                return View();
            }
        }

        private bool ValidarUsuario(string email, string senha)
        {
            var usuario = contexto.Usuarios.Single(u => u.Email == email);
            if (usuario != null)
            {
                return usuario.Senha == senha;
            }
            else
            {
                return false;
            }
        }

        private void CriarUsuario(Usuario Usuario)
        {
            contexto.Usuarios.Add(Usuario);
            contexto.SaveChanges();
        }
    }
}

MvcApp/Views/Conta/Entrar.cshtml
@model MvcApp.Models.LogOnModel

@{
    ViewBag.Title = "Entrar";
}

<hgroup class="title">
    <h1>Entrar.</h1>
    <h2>Coloque seu e-mail e senha abaixo.</h2>
</hgroup>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@Html.ValidationSummary(true, "Login sem sucesso. Tente novamente.")

@using (Html.BeginForm((string)ViewBag.FormAction, "Conta")) {
    <fieldset>
        <legend>Formulario de entrada</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.Email)
                @Html.TextBoxFor(m => m.Email)
                @Html.ValidationMessageFor(m => m.Email)
            </li>
            <li>
                @Html.LabelFor(m => m.Senha)
                @Html.PasswordFor(m => m.Senha)
                @Html.ValidationMessageFor(m => m.Senha)
            </li>
            <li>
                @Html.CheckBoxFor(m => m.Lembrar)
                @Html.LabelFor(m => m.Lembrar, new { @class = "checkbox" })
            </li>
        </ol>
        <input type="submit" value="Entrar" title="Entrar" />
    </fieldset>
    <p>
        @Html.ActionLink("Registrar", "Registrar") se você não tem uma conta.
    </p>
}

MvcApp/Views/Conta/Registrar.cshtml
@model Biblioteca.Modelos.Usuario

@{
    ViewBag.Title = "Registrar";
}

<hgroup class="title">
    <h1>Registrar.</h1>
    <h2>Use o formulário abaixo para criar uma nova conta.</h2>
</hgroup>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@Html.ValidationSummary(true, "Ocorreu um erro ao criar a conta, tente novamente.")

@using (Html.BeginForm((string)ViewBag.FormAction, "Conta")) {
    <fieldset>
        <legend>Registration Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.Nome)
                @Html.TextBoxFor(m => m.Nome)
                @Html.ValidationMessageFor(m => m.Nome)
            </li>
            <li>
                @Html.LabelFor(m => m.Email)
                @Html.TextBoxFor(m => m.Email)
                @Html.ValidationMessageFor(m => m.Email)
            </li>
            <li>
                @Html.LabelFor(m => m.Senha)
                @Html.PasswordFor(m => m.Senha)
                @Html.ValidationMessageFor(m => m.Senha)
            </li>
             <li>
                @Html.LabelFor(m => m.Apelido)
                @Html.TextBoxFor(m => m.Apelido)
                @Html.ValidationMessageFor(m => m.Apelido)
            </li>
        </ol>
        <input type="submit" value="Registrar" title="Registrar" />
    </fieldset>
}